name: Deploy Bot Automatically

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd ~/miixbankdiscord-bot
          git fetch origin
          git reset --hard origin/main
          pip3 install -r requirements.txt
          pkill -f main.py || true
          
          # إنهاء أي عملية معلقة داخل الجلسة أولاً وتمرير أمر التشغيل الجديد بأمان
          screen -S DiscordMiixBank -X q
          screen -dmS DiscordMiixBank python3 main.py