name: Deploy Bot Automatically

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@master
      continue-on-error: true  # السحر هنا: يمنع تلوين الأكشن بالأحمر عند انتهاء مهلة الاتصال
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        command_timeout: 15s
        script: |
          cd ~/M.Bank
          git fetch origin
          git reset --hard origin/main
          pip3 install -r requirements.txt
          
          # إنشاء ملف الـ .env تلقائياً وحقن التوكن بأمان
          echo "TOKEN=${{ secrets.DISCORD_TOKEN }}" > .env
          
          # إيقاف النسخة القديمة بأمان لحماية البوتات الأخرى
          pkill -f "M.Bank/main.py" || true
          
          # تشغيل البوت في الخلفية
          nohup python3 main.py > /dev/null 2>&1 &